In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/Josh/codeup-data-science/numpy-pandas-visualization-exercises/mytable_customer_details - Copy of Table1_CustDetails.csv')

In [3]:
df

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
0,0002-ORFBO,Female,True,0,Yes,Yes,3,1,True,1,...,$593.30,No,False,9,2020-10-25,$65.92,1 Year,One Line,DSL,phone_and_internet
1,0003-MKNFE,Male,False,0,No,No,0,2,True,1,...,$542.40,No,False,9,2020-10-25,$60.27,Month-to-Month,Two or More Lines,DSL,phone_and_internet
2,0004-TLHLJ,Male,False,0,No,No,0,1,True,2,...,$280.85,Yes,True,3,2021-04-25,$93.62,Month-to-Month,One Line,Fiber Optic,phone_and_internet
3,0011-IGKFF,Male,False,1,Yes,No,1,1,True,2,...,"$1,237.85",Yes,True,12,2020-07-26,$103.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
4,0013-EXCHZ,Female,True,1,Yes,No,1,1,True,2,...,$267.40,Yes,True,3,2021-04-25,$89.13,Month-to-Month,One Line,Fiber Optic,phone_and_internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Female,True,0,No,No,0,1,True,1,...,$742.90,No,False,13,2020-06-25,$57.15,1 Year,One Line,DSL,phone_and_internet
7039,9992-RRAMN,Male,False,0,Yes,No,1,2,True,2,...,"$1,873.70",Yes,True,22,2019-09-25,$85.17,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
7040,9992-UJOEL,Male,False,0,No,No,0,1,True,1,...,$92.75,No,False,1,2021-06-25,$92.75,Month-to-Month,One Line,DSL,phone_and_internet
7041,9993-LHIEB,Male,False,0,Yes,Yes,3,1,True,1,...,"$4,627.65",No,False,68,2015-11-26,$68.05,2 Year,One Line,DSL,phone_and_internet
7042,9995-HOTOH,Male,False,0,Yes,Yes,3,0,False,1,...,"$3,707.60",No,False,62,2016-05-27,$59.80,2 Year,No Phone Service,DSL,internet_only

In [4]:
churned = df[df['churn']=='Yes']

In [5]:
churned.size

46725

### Percentage of all customers that have churned

In [6]:
churned.size/df.size

0.2653698707936959

In [7]:
churned_month_to_month = churned[churned['contract_type.1'] == 'Month-to-Month']

In [8]:
churned_month_to_month

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
2,0004-TLHLJ,Male,False,0,No,No,0,1,True,2,...,$280.85,Yes,True,3,2021-04-25,$93.62,Month-to-Month,One Line,Fiber Optic,phone_and_internet
3,0011-IGKFF,Male,False,1,Yes,No,1,1,True,2,...,"$1,237.85",Yes,True,12,2020-07-26,$103.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
4,0013-EXCHZ,Female,True,1,Yes,No,1,1,True,2,...,$267.40,Yes,True,3,2021-04-25,$89.13,Month-to-Month,One Line,Fiber Optic,phone_and_internet
19,0023-HGHWL,Male,False,1,No,No,0,0,False,1,...,$25.10,Yes,True,1,2021-06-25,$25.10,Month-to-Month,No Phone Service,DSL,internet_only
21,0023-XUOPT,Female,True,0,Yes,No,1,2,True,2,...,"$1,215.60",Yes,True,12,2020-07-26,$101.30,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7017,9957-YODKZ,Male,False,1,No,No,0,2,True,2,...,$790.15,Yes,True,9,2020-10-25,$87.79,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
7025,9968-FFVVH,Female,True,0,Yes,Yes,3,0,False,1,...,$30.50,Yes,True,1,2021-06-25,$30.50,Month-to-Month,No Phone Service,DSL,internet_only
7036,9985-MWVIX,Female,True,0,No,No,0,1,True,2,...,$70.15,Yes,True,1,2021-06-25,$70.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7037,9986-BONCE,Female,True,0,No,No,0,1,True,0,...,$85.50,Yes,True,4,2021-03-26,$21.38,Month-to-Month,One Line,No Internet Service,phone_only
7039,9992-RRAMN,Male,False,0,Yes,No,1,2,True,2,...,"$1,873.70",Yes,True,22,2019-09-25,$85.17,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet

### Percentage of month to month users that have churned

In [9]:
churned_month_to_month.size/churned.size

0.8855002675227395

In [10]:
churned_phone_and_internet = churned[churned['service_type']=='phone_and_internet']
churned_phone_and_internet

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
2,0004-TLHLJ,Male,False,0,No,No,0,1,True,2,...,$280.85,Yes,True,3,2021-04-25,$93.62,Month-to-Month,One Line,Fiber Optic,phone_and_internet
3,0011-IGKFF,Male,False,1,Yes,No,1,1,True,2,...,"$1,237.85",Yes,True,12,2020-07-26,$103.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
4,0013-EXCHZ,Female,True,1,Yes,No,1,1,True,2,...,$267.40,Yes,True,3,2021-04-25,$89.13,Month-to-Month,One Line,Fiber Optic,phone_and_internet
18,0022-TCJCI,Male,False,1,No,No,0,1,True,1,...,"$2,791.50",Yes,True,44,2017-11-25,$63.44,1 Year,One Line,DSL,phone_and_internet
21,0023-XUOPT,Female,True,0,Yes,No,1,2,True,2,...,"$1,215.60",Yes,True,12,2020-07-26,$101.30,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7007,9940-RHLFB,Male,False,0,Yes,No,1,1,True,2,...,"$3,013.05",Yes,True,37,2018-06-26,$81.43,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7014,9950-MTGYX,Male,False,1,No,No,0,1,True,2,...,"$2,030.30",Yes,True,20,2019-11-25,$101.52,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7017,9957-YODKZ,Male,False,1,No,No,0,2,True,2,...,$790.15,Yes,True,9,2020-10-25,$87.79,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
7036,9985-MWVIX,Female,True,0,No,No,0,1,True,2,...,$70.15,Yes,True,1,2021-06-25,$70.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7039,9992-RRAMN,Male,False,0,Yes,No,1,2,True,2,...,"$1,873.70",Yes,True,22,2019-09-25,$85.17,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet

In [11]:
churned_phone_and_internet.size/churned.size

0.8485821294810059

In [12]:
churned_phone_and_internet.size/churned_month_to_month.size

0.9583081570996979

In [13]:
churned_internet = churned[churned['service_type']=='internet_only']

In [16]:
churned_internet.size

4250

In [14]:
churned_phone = churned[churned['service_type']=='phone_only']

In [15]:
churned_phone.size

2825

In [32]:
churned['tenure'].value_counts()

1     448
2      98
3      90
4      79
5      53
     ...
71      4
72      4
62      2
73      2
74      1
Name: tenure, Length: 74, dtype: int64

In [39]:
churned_one_month = churned[churned['tenure']==1]

In [43]:
churned_one_month['avg_monthly_charges']

19      $25.10
34      $91.10
57      $19.85
58      $99.75
80      $80.20
         ...
6965    $74.30
6974    $25.05
7001    $75.30
7025    $30.50
7036    $70.15
Name: avg_monthly_charges, Length: 448, dtype: object

In [45]:
churned_one_month.size/churned.size

0.2397003745318352

In [47]:
df[df['tenure']==1].size

18600