In [21]:
import pandas as pd
import numpy as np
import seaborn as sns

In [22]:
df = pd.read_csv('/Users/Josh/codeup-data-science/numpy-pandas-visualization-exercises/mytable_customer_details - Copy of Table1_CustDetails.csv')

In [23]:
df.head()

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
0,0002-ORFBO,Female,True,0,Yes,Yes,3,1,True,1,...,$593.30,No,False,9,2020-10-25,$65.92,1 Year,One Line,DSL,phone_and_internet
1,0003-MKNFE,Male,False,0,No,No,0,2,True,1,...,$542.40,No,False,9,2020-10-25,$60.27,Month-to-Month,Two or More Lines,DSL,phone_and_internet
2,0004-TLHLJ,Male,False,0,No,No,0,1,True,2,...,$280.85,Yes,True,3,2021-04-25,$93.62,Month-to-Month,One Line,Fiber Optic,phone_and_internet
3,0011-IGKFF,Male,False,1,Yes,No,1,1,True,2,...,"$1,237.85",Yes,True,12,2020-07-26,$103.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
4,0013-EXCHZ,Female,True,1,Yes,No,1,1,True,2,...,$267.40,Yes,True,3,2021-04-25,$89.13,Month-to-Month,One Line,Fiber Optic,phone_and_internet

In [56]:
fiber_optic = df[df['internet_service.1']=='Fiber Optic']

In [44]:
monthly_fiber = fiber_optic[fiber_optic['contract_type.1']=='Month-to-Month']
monthly_fiber

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
2,0004-TLHLJ,Male,False,0,No,No,0,1,True,2,...,$280.85,Yes,True,3,2021-04-25,$93.62,Month-to-Month,One Line,Fiber Optic,phone_and_internet
3,0011-IGKFF,Male,False,1,Yes,No,1,1,True,2,...,"$1,237.85",Yes,True,12,2020-07-26,$103.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
4,0013-EXCHZ,Female,True,1,Yes,No,1,1,True,2,...,$267.40,Yes,True,3,2021-04-25,$89.13,Month-to-Month,One Line,Fiber Optic,phone_and_internet
12,0018-NYROU,Female,True,0,Yes,No,1,1,True,2,...,$351.50,No,False,5,2021-02-23,$70.30,Month-to-Month,One Line,Fiber Optic,phone_and_internet
17,0021-IKXGC,Female,True,1,No,No,0,2,True,2,...,$72.10,No,False,1,2021-06-25,$72.10,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7017,9957-YODKZ,Male,False,1,No,No,0,2,True,2,...,$790.15,Yes,True,9,2020-10-25,$87.79,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
7021,9962-BFPDU,Male,False,1,Yes,Yes,3,2,True,2,...,"$3,625.20",No,False,33,2018-10-26,$109.85,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
7031,9974-JFBHQ,Male,False,0,No,Yes,2,1,True,2,...,"$6,171.20",No,False,62,2016-05-27,$99.54,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7036,9985-MWVIX,Female,True,0,No,No,0,1,True,2,...,$70.15,Yes,True,1,2021-06-25,$70.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7039,9992-RRAMN,Male,False,0,Yes,No,1,2,True,2,...,"$1,873.70",Yes,True,22,2019-09-25,$85.17,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet

In [47]:
monthly_fiber['service_type'].value_counts()

phone_and_internet    2127
Name: service_type, dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             7043 non-null   object
 1   gender                  7043 non-null   object
 2   is_female               7043 non-null   bool
 3   is_senior_citizen       7043 non-null   int64
 4   partner                 7043 non-null   object
 5   dependents              7043 non-null   object
 6   partner_dependents      7043 non-null   int64
 7   phone_service           7043 non-null   int64
 8   has_phone               7043 non-null   bool
 9   internet_service        7043 non-null   int64
 10  has_internet            7043 non-null   bool
 11  has_phone_and_internet  7043 non-null   bool
 12  contract_type           7043 non-null   int64
 13  payment_type            7043 non-null   object
 14  monthly_charges         7043 non-null   object
 15  total_charges           7032 non-null   object
 16  churn                   7043 non-null   object
 17  has_churned             7043 non-null   bool
 18  tenure                  7043 non-null   int64
 19  start_date              7043 non-null   object
 20  avg_monthly_charges     7043 non-null   object
 21  contract_type.1         7043 non-null   object
 22  phone_service.1         7043 non-null   object
 23  internet_service.1      7043 non-null   object
 24  service_type            7043 non-null   object
dtypes: bool(5), int64(6), object(14)
memory usage: 1.1+ MB

In [32]:
len(df[df['tenure']==1])

744

In [34]:
one_month = df[df['tenure']==1]

In [36]:
one_month['service_type'].value_counts()

phone_and_internet    478
phone_only            193
internet_only          73
Name: service_type, dtype: int64

In [37]:
one_month['internet_service.1'].value_counts()

Fiber Optic            293
DSL                    258
No Internet Service    193
Name: internet_service.1, dtype: int64

### Month-to-Month users

In [25]:
month_to_month = df[df['contract_type.1']=='Month-to-Month']
month_to_month

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
1,0003-MKNFE,Male,False,0,No,No,0,2,True,1,...,$542.40,No,False,9,2020-10-25,$60.27,Month-to-Month,Two or More Lines,DSL,phone_and_internet
2,0004-TLHLJ,Male,False,0,No,No,0,1,True,2,...,$280.85,Yes,True,3,2021-04-25,$93.62,Month-to-Month,One Line,Fiber Optic,phone_and_internet
3,0011-IGKFF,Male,False,1,Yes,No,1,1,True,2,...,"$1,237.85",Yes,True,12,2020-07-26,$103.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
4,0013-EXCHZ,Female,True,1,Yes,No,1,1,True,2,...,$267.40,Yes,True,3,2021-04-25,$89.13,Month-to-Month,One Line,Fiber Optic,phone_and_internet
5,0013-MHZWF,Female,True,0,No,Yes,2,1,True,1,...,$571.45,No,False,8,2020-11-24,$71.43,Month-to-Month,One Line,DSL,phone_and_internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7033,9975-SKRNR,Male,False,0,No,No,0,1,True,0,...,$18.90,No,False,1,2021-06-25,$18.90,Month-to-Month,One Line,No Internet Service,phone_only
7036,9985-MWVIX,Female,True,0,No,No,0,1,True,2,...,$70.15,Yes,True,1,2021-06-25,$70.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7037,9986-BONCE,Female,True,0,No,No,0,1,True,0,...,$85.50,Yes,True,4,2021-03-26,$21.38,Month-to-Month,One Line,No Internet Service,phone_only
7039,9992-RRAMN,Male,False,0,Yes,No,1,2,True,2,...,"$1,873.70",Yes,True,22,2019-09-25,$85.17,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
7040,9992-UJOEL,Male,False,0,No,No,0,1,True,1,...,$92.75,No,False,1,2021-06-25,$92.75,Month-to-Month,One Line,DSL,phone_and_internet

### Month-to-month users that churned

In [26]:
churned_month_to_month = month_to_month[month_to_month['churn']=='Yes']

In [27]:
churned_month_to_month.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1655 entries, 2 to 7039
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             1655 non-null   object
 1   gender                  1655 non-null   object
 2   is_female               1655 non-null   bool
 3   is_senior_citizen       1655 non-null   int64
 4   partner                 1655 non-null   object
 5   dependents              1655 non-null   object
 6   partner_dependents      1655 non-null   int64
 7   phone_service           1655 non-null   int64
 8   has_phone               1655 non-null   bool
 9   internet_service        1655 non-null   int64
 10  has_internet            1655 non-null   bool
 11  has_phone_and_internet  1655 non-null   bool
 12  contract_type           1655 non-null   int64
 13  payment_type            1655 non-null   object
 14  monthly_charges         1655 non-null   object
 15  total_charges           1655 non-null   object
 16  churn                   1655 non-null   object
 17  has_churned             1655 non-null   bool
 18  tenure                  1655 non-null   int64
 19  start_date              1655 non-null   object
 20  avg_monthly_charges     1655 non-null   object
 21  contract_type.1         1655 non-null   object
 22  phone_service.1         1655 non-null   object
 23  internet_service.1      1655 non-null   object
 24  service_type            1655 non-null   object
dtypes: bool(5), int64(6), object(14)
memory usage: 279.6+ KB

In [50]:
churned_month_to_month['internet_service.1'].value_counts()

Fiber Optic            1162
DSL                     394
No Internet Service      99
Name: internet_service.1, dtype: int64

In [55]:
churned_fiber = churned_month_to_month[churned_month_to_month['internet_service.1']=='Fiber Optic']
churned_fiber

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
2,0004-TLHLJ,Male,False,0,No,No,0,1,True,2,...,$280.85,Yes,True,3,2021-04-25,$93.62,Month-to-Month,One Line,Fiber Optic,phone_and_internet
3,0011-IGKFF,Male,False,1,Yes,No,1,1,True,2,...,"$1,237.85",Yes,True,12,2020-07-26,$103.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
4,0013-EXCHZ,Female,True,1,Yes,No,1,1,True,2,...,$267.40,Yes,True,3,2021-04-25,$89.13,Month-to-Month,One Line,Fiber Optic,phone_and_internet
21,0023-XUOPT,Female,True,0,Yes,No,1,2,True,2,...,"$1,215.60",Yes,True,12,2020-07-26,$101.30,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
47,0080-OROZO,Male,False,0,No,No,0,2,True,2,...,"$4,036.85",Yes,True,38,2018-05-27,$106.23,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7007,9940-RHLFB,Male,False,0,Yes,No,1,1,True,2,...,"$3,013.05",Yes,True,37,2018-06-26,$81.43,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7014,9950-MTGYX,Male,False,1,No,No,0,1,True,2,...,"$2,030.30",Yes,True,20,2019-11-25,$101.52,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7017,9957-YODKZ,Male,False,1,No,No,0,2,True,2,...,$790.15,Yes,True,9,2020-10-25,$87.79,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
7036,9985-MWVIX,Female,True,0,No,No,0,1,True,2,...,$70.15,Yes,True,1,2021-06-25,$70.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7039,9992-RRAMN,Male,False,0,Yes,No,1,2,True,2,...,"$1,873.70",Yes,True,22,2019-09-25,$85.17,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet

In [29]:
churned_month_to_month['tenure'].value_counts()

1     446
2      98
3      90
4      77
5      53
     ...
55      1
61      1
62      1
69      1
70      1
Name: tenure, Length: 70, dtype: int64

In [18]:
churned_1_month = churned_month_to_month[churned_month_to_month['tenure']==1]
churned_1_month

,customer_id,gender,is_female,is_senior_citizen,partner,dependents,partner_dependents,phone_service,has_phone,internet_service,...,total_charges,churn,has_churned,tenure,start_date,avg_monthly_charges,contract_type.1,phone_service.1,internet_service.1,service_type
19,0023-HGHWL,Male,False,1,No,No,0,0,False,1,...,$25.10,Yes,True,1,2021-06-25,$25.10,Month-to-Month,No Phone Service,DSL,internet_only
34,0056-EPFBG,Male,False,1,No,No,0,1,True,1,...,$91.10,Yes,True,1,2021-06-25,$91.10,Month-to-Month,One Line,DSL,phone_and_internet
57,0098-BOWSO,Male,False,0,No,No,0,1,True,0,...,$19.85,Yes,True,1,2021-06-25,$19.85,Month-to-Month,One Line,No Internet Service,phone_only
58,0100-DUVFC,Male,False,0,No,Yes,2,2,True,2,...,$99.75,Yes,True,1,2021-06-25,$99.75,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
80,0129-QMPDR,Female,True,0,No,No,0,2,True,2,...,$80.20,Yes,True,1,2021-06-25,$80.20,Month-to-Month,Two or More Lines,Fiber Optic,phone_and_internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6965,9885-AIBVB,Female,True,0,No,No,0,1,True,2,...,$74.30,Yes,True,1,2021-06-25,$74.30,Month-to-Month,One Line,Fiber Optic,phone_and_internet
6974,9896-UYMIE,Female,True,1,No,No,0,0,False,1,...,$25.05,Yes,True,1,2021-06-25,$25.05,Month-to-Month,No Phone Service,DSL,internet_only
7001,9933-QRGTX,Female,True,0,No,No,0,1,True,2,...,$75.30,Yes,True,1,2021-06-25,$75.30,Month-to-Month,One Line,Fiber Optic,phone_and_internet
7025,9968-FFVVH,Female,True,0,Yes,Yes,3,0,False,1,...,$30.50,Yes,True,1,2021-06-25,$30.50,Month-to-Month,No Phone Service,DSL,internet_only
7036,9985-MWVIX,Female,True,0,No,No,0,1,True,2,...,$70.15,Yes,True,1,2021-06-25,$70.15,Month-to-Month,One Line,Fiber Optic,phone_and_internet

### Percentage of users that churned in one month

In [19]:
len(churned_1_month)/len(churned_month_to_month)

0.26948640483383685

In [17]:
phone_and_internet = churned_1_month[churned_1_month['service_type']=='phone_and_internet']
phone_and_internet['avg_monthly_charges']

34       $91.10
58       $99.75
80       $80.20
87       $70.90
121     $167.30
         ...
6921     $45.70
6960     $78.45
6965     $74.30
7001     $75.30
7036     $70.15
Name: avg_monthly_charges, Length: 335, dtype: object

In [ ]:
phone_and_internet[phone_and_internet['avg_monthly_charges']